volumes: []

transmission:
  enabled: true
  image: linuxserver/transmission
  env:
    PUID: "1000"
    PGID: "100"
    TZ: Etc/UTC
  resources: {}
  volumeMounts: []

qbittorrent:
  enabled: true
  image: lscr.io/linuxserver/qbittorrent:latest
  ports:
    webui: 3000
    torrenting: 6881
  env:
    PUID: "1000"
    PGID: "100"
    TZ: Etc/UTC

gluetun:
  image: qmcgaw/gluetun:v3
  resources: {}
  env:
    HEALTH_VPN_DURATION_INITIAL: 120s
    BLOCK_MALICIOUS: "off"
    DNS_KEEP_NAMESERVER: "on"
    FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/15
  envFrom: []

busybox:
  image: busybox
  resources: {}
