{{ range $name, $data := .Values.services }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- if $data.labels }}
    {{ range $i, $val := $data.labels }}
        {{- $parts := splitList "=" $val -}}
    "{{ index $parts 0 }}": "{{ index $parts 1 }}"
    {{ end }}
    {{- end }}
spec:
    replicas: {{ $data.replicas | default 1 }}
    selector:
        matchLabels:
            app: {{ $name }}
    template:
        metadata:
            labels:
                app: {{ $name }}
        spec:
            {{ if $data.volumes -}}
            volumes:
            {{ range $volname, $_ := $data.volumes }}
                -   name: "{{ $volname }}"
                    persistentVolumeClaim:
                        claimName: "{{ $volname }}"
            {{- end }}
            {{- end }}

            containers:
                -   name: {{ $name }}
                    image: {{ $data.image | quote }}
                    ports:
                    {{ range $p := $data.ports }}
                        -   containerPort: {{ $p.port }}
                            protocol: {{ $p.protocol | default "TCP" | quote }}
                    {{ end }}
                    {{ if $data.volumes }}
                    volumeMounts:
                    {{ range $volname, $mountPath := $data.volumes }}
                        -   name: {{ $volname | quote }}
                            mountPath: {{ $mountPath | quote }}
                    {{ end }}
                    {{ end }}
                    {{ if $data.envFrom}}
                    envFrom:
                        {{ $data.envFrom | toYaml | nindent 26 }}
                    {{ end }}
                    {{ if $data.environment }}
                    env:
                        {{ range $key, $value := $data.environment }}
                        -   name: {{ $key | quote }}
                            value: {{ $value | quote }}
                        {{ end }}
                    {{ end }}
                    {{ if $data.command }}
                    command:
                        {{ $data.command | toYaml | nindent 26 }}
                    {{ end }}
                    {{ if $data.args }}
                    args:
                        {{ range $cmd := $data.args }}
                        -   {{ $cmd | quote }}
                        {{ end }}
                    {{ end }}
                
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- if $data.serviceAnnotations }}
    {{ $data.serviceAnnotations | toYaml | nindent 4 }}
    {{- end }}
spec:
    selector:
        app: {{ $name }}
    type: {{ $data.serviceType | default "ClusterIP" | quote }}
    ports:
        {{ range $port := $data.ports }}
        -   name: {{ $port.name | default "http" | quote }}
            port: {{ $port.port }}
            protocol: {{ $port.protocol | default "TCP" | quote }}
            targetPort: {{ $port.port }}
        {{ end }}

{{ end }}